export const FABRIC_LIST_REQUEST = 'FABRIC_LIST_REQUEST'
export const FABRIC_LIST_SUCCESS = 'FABRIC_LIST_SUCCESS'
export const FABRIC_LIST_FAIL = 'FABRIC_LIST_FAIL'
export const FABRIC_LIST_RESET = 'FABRIC_LIST_RESET'

export const FABRIC_CREATE_REQUEST = 'FABRIC_CREATE_REQUEST'
export const FABRIC_CREATE_SUCCESS = 'FABRIC_CREATE_SUCCESS'
export const FABRIC_CREATE_FAIL = 'FABRIC_CREATE_FAIL'
export const FABRIC_CREATE_RESET = 'FABRIC_CREATE_RESET'

export const FABRIC_EDIT_REQUEST = 'FABRIC_EDIT_REQUEST'
export const FABRIC_EDIT_SUCCESS = 'FABRIC_EDIT_SUCCESS'
export const FABRIC_EDIT_FAIL = 'FABRIC_EDIT_FAIL'
export const FABRIC_EDIT_RESET = 'FABRIC_EDIT_RESET'

export const FABRIC_DELETE_REQUEST = 'FABRIC_DELETE_REQUEST'
export const FABRIC_DELETE_SUCCESS = 'FABRIC_DELETE_SUCCESS'
export const FABRIC_DELETE_FAIL = 'FABRIC_DELETE_FAIL'
export const FABRIC_DELETE_RESET = 'FABRIC_DELETE_RESET'

export const FABRIC_LIST_ALL_REQUEST = 'FABRIC_LIST_ALL_REQUEST'
export const FABRIC_LIST_ALL_SUCCESS = 'FABRIC_LIST_ALL_SUCCESS'
export const FABRIC_LIST_ALL_FAIL = 'FABRIC_LIST_ALL_FAIL'
export const FABRIC_LIST_ALL_RESET = 'FABRIC_LIST_ALL_RESET'