export const STORY_LIST_REQUEST = 'STORY_LIST_REQUEST'
export const STORY_LIST_SUCCESS = 'STORY_LIST_SUCCESS'
export const STORY_LIST_FAIL = 'STORY_LIST_FAIL'
export const STORY_LIST_RESET = 'STORY_LIST_RESET'

export const STORY_CREATE_REQUEST = 'STORY_CREATE_REQUEST'
export const STORY_CREATE_SUCCESS = 'STORY_CREATE_SUCCESS'
export const STORY_CREATE_FAIL = 'STORY_CREATE_FAIL'
export const STORY_CREATE_RESET = 'STORY_CREATE_RESET'

export const STORY_EDIT_REQUEST = 'STORY_EDIT_REQUEST'
export const STORY_EDIT_SUCCESS = 'STORY_EDIT_SUCCESS'
export const STORY_EDIT_FAIL = 'STORY_EDIT_FAIL'
export const STORY_EDIT_RESET = 'STORY_EDIT_RESET'

export const STORY_DELETE_REQUEST = 'STORY_DELETE_REQUEST'
export const STORY_DELETE_SUCCESS = 'STORY_DELETE_SUCCESS'
export const STORY_DELETE_FAIL = 'STORY_DELETE_FAIL'
export const STORY_DELETE_RESET = 'STORY_DELETE_RESET'

export const STORY_LIST_ALL_REQUEST = 'STORY_LIST_ALL_REQUEST'
export const STORY_LIST_ALL_SUCCESS = 'STORY_LIST_ALL_SUCCESS'
export const STORY_LIST_ALL_FAIL = 'STORY_LIST_ALL_FAIL'
export const STORY_LIST_ALL_RESET = 'STORY_LIST_ALL_RESET'