export const STYLE_LIST_REQUEST = 'STYLE_LIST_REQUEST'
export const STYLE_LIST_SUCCESS = 'STYLE_LIST_SUCCESS'
export const STYLE_LIST_FAIL = 'STYLE_LIST_FAIL'
export const STYLE_LIST_RESET = 'STYLE_LIST_RESET'

export const STYLE_CREATE_REQUEST = 'STYLE_CREATE_REQUEST'
export const STYLE_CREATE_SUCCESS = 'STYLE_CREATE_SUCCESS'
export const STYLE_CREATE_FAIL = 'STYLE_CREATE_FAIL'
export const STYLE_CREATE_RESET = 'STYLE_CREATE_RESET'

export const STYLE_EDIT_REQUEST = 'STYLE_EDIT_REQUEST'
export const STYLE_EDIT_SUCCESS = 'STYLE_EDIT_SUCCESS'
export const STYLE_EDIT_FAIL = 'STYLE_EDIT_FAIL'
export const STYLE_EDIT_RESET = 'STYLE_EDIT_RESET'

export const STYLE_DELETE_REQUEST = 'STYLE_DELETE_REQUEST'
export const STYLE_DELETE_SUCCESS = 'STYLE_DELETE_SUCCESS'
export const STYLE_DELETE_FAIL = 'STYLE_DELETE_FAIL'
export const STYLE_DELETE_RESET = 'STYLE_DELETE_RESET'

export const STYLE_LIST_ALL_REQUEST = 'STYLE_LIST_ALL_REQUEST'
export const STYLE_LIST_ALL_SUCCESS = 'STYLE_LIST_ALL_SUCCESS'
export const STYLE_LIST_ALL_FAIL = 'STYLE_LIST_ALL_FAIL'
export const STYLE_LIST_ALL_RESET = 'STYLE_LIST_ALL_RESET'

export const STYLE_BY_ID_REQUEST = 'STYLE_BY_ID_REQUEST'
export const STYLE_BY_ID_SUCCESS = 'STYLE_BY_ID_SUCCESS'
export const STYLE_BY_ID_FAIL = 'STYLE_BY_ID_FAIL'
export const STYLE_BY_ID_RESET = 'STYLE_BY_ID_RESET'

export const STYLE_CODE_REQUEST = 'STYLE_CODE_REQUEST'
export const STYLE_CODE_SUCCESS = 'STYLE_CODE_SUCCESS'
export const STYLE_CODE_FAIL = 'STYLE_CODE_FAIL'
export const STYLE_CODE_RESET = 'STYLE_CODE_RESET'