export const VENDOR_LIST_REQUEST = 'VENDOR_LIST_REQUEST'
export const VENDOR_LIST_SUCCESS = 'VENDOR_LIST_SUCCESS'
export const VENDOR_LIST_FAIL = 'VENDOR_LIST_FAIL'
export const VENDOR_LIST_RESET = 'VENDOR_LIST_RESET'

export const VENDOR_CREATE_REQUEST = 'VENDOR_CREATE_REQUEST'
export const VENDOR_CREATE_SUCCESS = 'VENDOR_CREATE_SUCCESS'
export const VENDOR_CREATE_FAIL = 'VENDOR_CREATE_FAIL'
export const VENDOR_CREATE_RESET = 'VENDOR_CREATE_RESET'

export const VENDOR_EDIT_REQUEST = 'VENDOR_EDIT_REQUEST'
export const VENDOR_EDIT_SUCCESS = 'VENDOR_EDIT_SUCCESS'
export const VENDOR_EDIT_FAIL = 'VENDOR_EDIT_FAIL'
export const VENDOR_EDIT_RESET = 'VENDOR_EDIT_RESET'

export const VENDOR_DELETE_REQUEST = 'VENDOR_DELETE_REQUEST'
export const VENDOR_DELETE_SUCCESS = 'VENDOR_DELETE_SUCCESS'
export const VENDOR_DELETE_FAIL = 'VENDOR_DELETE_FAIL'
export const VENDOR_DELETE_RESET = 'VENDOR_DELETE_RESET'

export const VENDOR_LIST_ALL_REQUEST = 'VENDOR_LIST_ALL_REQUEST'
export const VENDOR_LIST_ALL_SUCCESS = 'VENDOR_LIST_ALL_SUCCESS'
export const VENDOR_LIST_ALL_FAIL = 'VENDOR_LIST_ALL_FAIL'
export const VENDOR_LIST_ALL_RESET = 'VENDOR_LIST_ALL_RESET'